mod_id=soullife
mod_name=SoulLife SMP
mod_version=1.1.0
mod_group=com.soullife
mod_description=A hardcore death mod for Minecraft SMP servers
mod_license=MIT
mod_authors=Neoxy996

# Forge 1.20.1
forge_version=47.3.0

# Fabric
fabric_loader_version=0.15.11
fabric_api_version=0.92.0+1.20.1

# Balm
balm_version=7.3.43

org.gradle.jvmargs=-Xmx4G
