plugins {
    id 'net.neoforged.gradle.userdev' version '7.0.+'
    id 'java'
    id 'maven-publish'
}

group = 'com.soullife'
version = '1.1.0'
archivesBaseName = 'SoulLife-neoforge-1.21.1'

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
    withSourcesJar()
}

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
    }
    client { workingDirectory project.file('run') }
    server { workingDirectory project.file('run') }
}

dependencies {
    implementation "net.neoforged:neoforge:21.0.144"
}

sourceSets.main {
    java.srcDirs   += ['../common/src/main/java']
    resources.srcDirs += ['../common/src/main/resources']
}

jar {
    manifest { attributes(['Specification-Title': 'soullife', 'Implementation-Version': project.version]) }
}
